# Generated by Django 3.1 on 2020-08-15 04:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=1024)),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=4096)),
                ('category', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional')], max_length=128, null=True)),
                ('city', models.CharField(max_length=128)),
                ('tags', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
